# Site settings
title:          Shutter Clicks
description:    "Snapshots of my interests"
url:            "https://www.lycarter.com"

# Author
author:
  name:         Landon Carter
  url:          https://www.lycarter.com
  email:        me@lycarter.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       10
